$ExcludedProperties = @(
    'CanonicalName'
    'CN'
    'Created'
    'createTimeStamp'
    'Description'
    'DisplayName'
    'DistinguishedName'
    'Modified'
    'modifyTimeStamp'
    'Name'
    'ObjectGUID'
    'uSNChanged'
    'uSNCreated'
    'whenChanged'
    'whenCreated'
)