#Requires -Modules Pester

<#
    Integration tests for the clone engine kernel (ticket #25).

    These tests run against a LIVE lab forest and perform real AD writes into
    the Certificate Templates and OID containers. They are self-cleaning
    (AfterEach removes every object they create) and use deterministic,
    ADCSGoat-owned test names so they never collide with real templates.

    Run only where a writable lab DC is available. In CI or on machines without
    a DC, the whole Describe block is skipped.
#>

BeforeDiscovery {
    $script:LabAvailable = $false
    try {
        $rootDSE = New-Object System.DirectoryServices.DirectoryEntry('LDAP://RootDSE')
        $null = $rootDSE.configurationNamingContext
        $script:LabAvailable = $true
    } catch {
        $script:LabAvailable = $false
    }
}

BeforeAll {
    . $PSScriptRoot/../Public/Copy-AGTemplate.ps1
    . $PSScriptRoot/../Private/New-AGTemplateOid.ps1
    . $PSScriptRoot/../Private/Remove-AGTemplate.ps1

    Add-Type -AssemblyName System.DirectoryServices

    $script:RootDSE = New-Object System.DirectoryServices.DirectoryEntry('LDAP://RootDSE')
    $script:ConfigNC = $script:RootDSE.configurationNamingContext
    $script:TemplatesDN = "CN=Certificate Templates,CN=Public Key Services,CN=Services,$($script:ConfigNC)"
    $script:OidDN = "CN=OID,CN=Public Key Services,CN=Services,$($script:ConfigNC)"

    # Deterministic test-only destination names, all owned-marked on creation.
    $script:TestName = 'AGKernTest-Clone'
    $script:TestFallback = "$($script:TestName) Generated by ADCSGoat"
    $script:ForeignName = 'AGKernTest-Foreign'

    # Identity attributes never copied (skip list) plus attributes the design
    # intentionally governs on the clone: schema upgrade, fresh revision
    # counters, and the ownership marker. Those have dedicated tests below.
    $script:SkipList = @(
        'cn','name','objectClass','objectGUID','distinguishedName','instanceType',
        'whenCreated','whenChanged','uSNCreated','uSNChanged','dSCorePropagationData',
        'nTSecurityDescriptor','objectCategory','showInAdvancedViewOnly','displayName',
        'msPKI-Cert-Template-OID',
        'msPKI-Template-Schema-Version','revision','msPKI-Template-Minor-Revision',
        'description'
    )

    function script:Get-TemplateEntry {
        param([string]$Name)
        $path = "LDAP://CN=$Name,$($script:TemplatesDN)"
        if ([System.DirectoryServices.DirectoryEntry]::Exists($path)) {
            New-Object System.DirectoryServices.DirectoryEntry($path)
        } else { $null }
    }

    function script:Remove-TestObject {
        param([string]$Name)
        $entry = Get-TemplateEntry -Name $Name
        if ($null -ne $entry) {
            # capture OID companion for cleanup
            $oidValue = $entry.Properties['msPKI-Cert-Template-OID'].Value
            $entry.DeleteTree()
            $entry.Dispose()
            if ($oidValue) {
                $oidContainer = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:OidDN)")
                foreach ($child in @($oidContainer.Children)) {
                    if ($child.Properties['msPKI-Cert-Template-OID'].Value -eq $oidValue) {
                        $child.DeleteTree()
                    }
                    $child.Dispose()
                }
                $oidContainer.Dispose()
            }
        }
    }

    function script:Get-SdPart {
        param([System.DirectoryServices.DirectoryEntry]$Entry)
        $sd = $Entry.ObjectSecurity
        [pscustomobject]@{
            Owner  = $sd.GetOwner([System.Security.Principal.SecurityIdentifier]).Value
            Group  = $sd.GetGroup([System.Security.Principal.SecurityIdentifier]).Value
            Sddl   = $sd.GetSecurityDescriptorSddlForm([System.Security.AccessControl.AccessControlSections]::All)
            Binary = $sd.GetSecurityDescriptorBinaryForm()
        }
    }
}

Describe 'Copy-AGTemplate (integration)' -Skip:(-not $script:LabAvailable) {

    AfterAll {
        Remove-TestObject -Name $script:TestName
        Remove-TestObject -Name $script:TestFallback
        Remove-TestObject -Name $script:ForeignName
    }

    Context 'Happy-path clone of a v1 source (User)' {
        BeforeAll {
            $script:Result = Copy-AGTemplate -SourceName 'User' -DestinationName $script:TestName -Force
            $script:Source = Get-TemplateEntry -Name 'User'
            $script:Clone = Get-TemplateEntry -Name $script:TestName
        }

        It 'Creates the destination object' {
            $script:Clone | Should -Not -BeNullOrEmpty
        }

        It 'Sets destination identity (cn/name/displayName)' {
            $script:Clone.Properties['name'].Value | Should -Be $script:TestName
            $script:Clone.Properties['displayName'].Value | Should -Be $script:TestName
        }

        It 'Carries the ADCSGoat ownership marker' {
            "$($script:Clone.Properties['description'].Value)" | Should -Match 'Generated by ADCSGoat'
        }

        It 'Copies all non-excluded content attributes verbatim' {
            foreach ($prop in $script:Source.Properties.PropertyNames) {
                if ($script:SkipList -contains $prop) { continue }
                $srcValues = @($script:Source.Properties[$prop] | ForEach-Object { "$_" }) | Sort-Object
                $dstValues = @($script:Clone.Properties[$prop] | ForEach-Object { "$_" }) | Sort-Object
                ($dstValues -join '|') | Should -Be ($srcValues -join '|') -Because "attribute '$prop' must copy verbatim"
            }
        }

        It 'Upgrades a v1 source to schema v2 (GUI-authentic)' {
            [int]$script:Clone.Properties['msPKI-Template-Schema-Version'].Value | Should -Be 2
        }

        It 'Resets revision counters to fresh initial values' {
            [int]$script:Clone.Properties['msPKI-Template-Minor-Revision'].Value | Should -BeLessOrEqual 2
        }

        It 'Mints a fresh OID under the forest base arc, distinct from the source' {
            $forestBase = (New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:OidDN)")).Properties['msPKI-Cert-Template-OID'].Value
            $cloneOid = $script:Clone.Properties['msPKI-Cert-Template-OID'].Value
            $cloneOid | Should -Not -BeNullOrEmpty
            $cloneOid | Should -BeLike "$forestBase.*"
            $cloneOid | Should -Not -Be $script:Source.Properties['msPKI-Cert-Template-OID'].Value
        }

        It 'Creates a companion ms-PKI-Enterprise-Oid object resolving OID to display name' {
            $cloneOid = $script:Clone.Properties['msPKI-Cert-Template-OID'].Value
            $oidContainer = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:OidDN)")
            $match = @($oidContainer.Children | Where-Object {
                $_.Properties['msPKI-Cert-Template-OID'].Value -eq $cloneOid
            })
            $match | Should -HaveCount 1
            "$($match[0].Properties['displayName'].Value)" | Should -Be $script:TestName
        }

        It 'Copies the source security descriptor (owner/group/DACL/SACL/protected bit)' {
            $src = Get-SdPart -Entry $script:Source
            $dst = Get-SdPart -Entry $script:Clone
            $dst.Owner | Should -Be $src.Owner
            $dst.Group | Should -Be $src.Group
            # SDDL compare covers DACL+SACL+control flags
            $dst.Sddl | Should -Be $src.Sddl
        }
    }

    Context 'Schema v2 source copies verbatim (Workstation Authentication)' {
        BeforeAll {
            $null = Copy-AGTemplate -SourceName 'Workstation' -DestinationName $script:TestName -Force
            $script:Clone = Get-TemplateEntry -Name $script:TestName
        }

        It 'Keeps schema version 2 (no downgrade/upgrade churn)' {
            [int]$script:Clone.Properties['msPKI-Template-Schema-Version'].Value | Should -Be 2
        }
    }

    Context 'Collision handling' {
        It 'Replaces an owned collision with -Force and mints a new OID' {
            Copy-AGTemplate -SourceName 'User' -DestinationName $script:TestName -Force | Out-Null
            $firstOid = (Get-TemplateEntry -Name $script:TestName).Properties['msPKI-Cert-Template-OID'].Value
            Copy-AGTemplate -SourceName 'User' -DestinationName $script:TestName -Force | Out-Null
            $secondOid = (Get-TemplateEntry -Name $script:TestName).Properties['msPKI-Cert-Template-OID'].Value
            $secondOid | Should -Not -Be $firstOid
        }

        It 'Refuses to touch an unowned collision and uses the marked fallback name' {
            # Ensure the destination name slot is clean before planting the
            # foreign object (a prior test run may have left debris).
            Remove-TestObject -Name $script:TestName
            Remove-TestObject -Name $script:TestFallback

            # Foreign object: same destination name, NO ownership marker.
            $container = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:TemplatesDN)")
            $foreign = $container.Children.Add("CN=$($script:TestName)", 'pKICertificateTemplate')
            $foreign.Properties['displayName'].Value = $script:TestName
            $foreign.CommitChanges()
            $foreign.Dispose()
            $container.Dispose()

            Copy-AGTemplate -SourceName 'User' -DestinationName $script:TestName -Force | Out-Null

            # Foreign object untouched (still markerless)
            $stillForeign = Get-TemplateEntry -Name $script:TestName
            "$($stillForeign.Properties['description'].Value)" | Should -Not -Match 'Generated by ADCSGoat'

            # Clone landed at the deterministic fallback name
            $fallback = Get-TemplateEntry -Name $script:TestFallback
            $fallback | Should -Not -BeNullOrEmpty
            "$($fallback.Properties['description'].Value)" | Should -Match 'Generated by ADCSGoat'
        }
    }
}
