#Requires -Modules Pester

<#
    Integration tests for the ESC4 scenario deploy (ticket #28).

    "Test SSL" is a Web Server clone with ZERO attribute overrides — the
    vulnerability is purely the Domain Users Full Control ACE. These tests run
    against the live lab forest and are self-cleaning.
#>

BeforeDiscovery {
    $script:LabAvailable = $false
    try {
        $rootDSE = New-Object System.DirectoryServices.DirectoryEntry('LDAP://RootDSE')
        $null = $rootDSE.configurationNamingContext
        $script:LabAvailable = $true
    } catch {
        $script:LabAvailable = $false
    }
}

BeforeAll {
    . $PSScriptRoot/../Public/Deploy-AGEsc4.ps1
    . $PSScriptRoot/../Public/Copy-AGTemplate.ps1
    . $PSScriptRoot/../Private/New-AGTemplateOid.ps1
    . $PSScriptRoot/../Private/Remove-AGTemplate.ps1
    . $PSScriptRoot/../Private/Get-AGEnrollmentService.ps1
    . $PSScriptRoot/../Private/New-AGDeployState.ps1
    . $PSScriptRoot/../Private/Save-AGDeployState.ps1
    . $PSScriptRoot/../Private/Read-AGDeployState.ps1
    . $PSScriptRoot/../Private/Get-ADDomainNameFromNc.ps1
    . $PSScriptRoot/../Private/Invoke-AGTemplateScenario.ps1

    $script:RootDSE = New-Object System.DirectoryServices.DirectoryEntry('LDAP://RootDSE')
    $script:ConfigNC = $script:RootDSE.configurationNamingContext
    $script:TemplatesDN = "CN=Certificate Templates,CN=Public Key Services,CN=Services,$($script:ConfigNC)"
    $script:OidDN = "CN=OID,CN=Public Key Services,CN=Services,$($script:ConfigNC)"
    $script:CaDn = "CN=LabRootCA1,CN=Enrollment Services,CN=Public Key Services,CN=Services,$($script:ConfigNC)"
    $script:StatePath = Join-Path -Path $TestDrive -ChildPath 'ADCSGoat.State.xml'

    # Attributes the kernel legitimately governs on the clone (identity,
    # fresh OID, schema upgrade, revision counters, ownership marker) — these
    # are excluded from the "no attribute overrides" comparison.
    $script:KernelGoverned = @(
        'cn','name','displayName','distinguishedName','objectGUID',
        'msPKI-Cert-Template-OID','msPKI-Template-Schema-Version','revision',
        'msPKI-Template-Minor-Revision','description','whenCreated','whenChanged',
        'uSNCreated','uSNChanged','instanceType','dSCorePropagationData',
        'nTSecurityDescriptor','objectClass','objectCategory'
    )

    function script:Get-TemplateEntry {
        param([string]$Name)
        $path = "LDAP://CN=$Name,$($script:TemplatesDN)"
        if ([System.DirectoryServices.DirectoryEntry]::Exists($path)) {
            $entry = New-Object System.DirectoryServices.DirectoryEntry($path)
            $entry.RefreshCache()
            $entry
        } else { $null }
    }

    function script:Get-TemplateSddl {
        param([string]$Name)
        $e = Get-TemplateEntry -Name $Name
        $s = $e.ObjectSecurity.GetSecurityDescriptorSddlForm([System.Security.AccessControl.AccessControlSections]::All)
        $e.Dispose()
        $s
    }

    function script:Remove-ScenarioClone {
        param([string]$Name)
        $entry = Get-TemplateEntry -Name $Name
        if ($null -ne $entry) {
            $oidValue = "$($entry.Properties['msPKI-Cert-Template-OID'].Value)"
            $entry.DeleteTree()
            $entry.Dispose()
            if ($oidValue) {
                $oidContainer = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:OidDN)")
                foreach ($child in @($oidContainer.Children)) {
                    if ("$($child.Properties['msPKI-Cert-Template-OID'].Value)" -eq $oidValue) { $child.DeleteTree() }
                    $child.Dispose()
                }
                $oidContainer.Dispose()
            }
        }
        $ca = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:CaDn)")
        $ca.RefreshCache()
        $current = @($ca.Properties['certificateTemplates'] | ForEach-Object { "$_" })
        if ($current -contains $Name) {
            $ca.Properties['certificateTemplates'].Remove($Name)
            $ca.CommitChanges()
        }
        $ca.Dispose()
    }
}

Describe 'Deploy-AGEsc4 (live forest)' -Skip:(-not $script:LabAvailable) {

    AfterAll {
        Remove-ScenarioClone -Name 'Test SSL'
        Remove-ScenarioClone -Name 'Test SSL Generated by ADCSGoat'
        Remove-Item -Path $script:StatePath -ErrorAction Ignore
    }

    Context 'When deployed against the single-CA lab' {
        BeforeAll {
            $script:SourceBefore = Get-TemplateEntry -Name 'WebServer'
            $script:SourcePropsBefore = @{}
            foreach ($p in $script:SourceBefore.Properties.PropertyNames) {
                $script:SourcePropsBefore[$p] = @($script:SourceBefore.Properties[$p] | ForEach-Object { "$_" }) | Sort-Object
            }
            $script:SourceSddlBefore = $script:SourceBefore.ObjectSecurity.GetSecurityDescriptorSddlForm([System.Security.AccessControl.AccessControlSections]::All)

            $script:Result = Deploy-AGEsc4 -StatePath $script:StatePath -Force
            $script:Clone = Get-TemplateEntry -Name $script:Result.CloneCn
        }

        It 'Creates the clone at the expected name' {
            $script:Result.CloneCn | Should -Be 'Test SSL'
            $script:Clone | Should -Not -BeNullOrEmpty
        }

        It 'Applies zero attribute overrides beyond the kernel-governed set' {
            foreach ($p in $script:Clone.Properties.PropertyNames) {
                if ($script:KernelGoverned -contains $p) { continue }
                $cloneVals = @($script:Clone.Properties[$p] | ForEach-Object { "$_" }) | Sort-Object
                $srcVals = $script:SourcePropsBefore[$p]
                ($cloneVals -join '|') | Should -Be ($srcVals -join '|') -Because "ESC4 makes no attribute override on '$p'"
            }
        }

        It 'Is schema v2 (GUI-authentic upgrade of the v1 source)' {
            [int]$script:Clone.Properties['msPKI-Template-Schema-Version'].Value | Should -Be 2
        }

        It 'Grants Domain Users Full Control (GenericAll) on the clone' {
            $sddl = Get-TemplateSddl -Name $script:Result.CloneCn
            # GenericAll may render as the 'GA' shorthand or as the decomposed
            # rights mask (CCDCLCSWRPWPDTLOCRSDRCWDWO) depending on how the ACE
            # was written; both are Full Control. Trustee is the 'DU' alias or
            # the full Domain Users SID.
            $sddl | Should -Match "\(A;;(GA|CCDCLCSWRPWPDTLO[A-Z]*CRSDRCWDWO);;;(DU|S-1-5-21-\d+-\d+-\d+-513)\)"
        }
        It 'Keeps the copied source DACL intact underneath the grant' {
            # The source's Authenticated Users read ACE must survive.
            $sddl = Get-TemplateSddl -Name $script:Result.CloneCn
            $sddl | Should -Match '\(A;;LCRPLORC;;;AU\)'
        }

        It 'Publishes the clone cn in the selected CA certificateTemplates' {
            $ca = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:CaDn)")
            $ca.RefreshCache()
            $published = @($ca.Properties['certificateTemplates'] | ForEach-Object { "$_" })
            $ca.Dispose()
            $published | Should -Contain $script:Result.CloneCn
        }

        It 'Records the clone in the state file (cn, OID, companion DN)' {
            $state = Read-AGDeployState -Path $script:StatePath
            $records = @($state.Clones | Where-Object { $_.Scenario -eq 'ESC4' })
            $records | Should -HaveCount 1
            $records[0].Cn | Should -Be $script:Result.CloneCn
            $records[0].Oid | Should -Be $script:Result.Oid
            $records[0].CompanionOidObjectDN | Should -Match 'CN=OID'
        }

        It 'Leaves the Web Server source attributes unchanged' {
            $sourceAfter = Get-TemplateEntry -Name 'WebServer'
            foreach ($p in $sourceAfter.Properties.PropertyNames) {
                $after = @($sourceAfter.Properties[$p] | ForEach-Object { "$_" }) | Sort-Object
                ($after -join '|') | Should -Be (($script:SourcePropsBefore[$p]) -join '|') -Because "source attribute '$p' must not change"
            }
            $sourceAfter.Dispose()
        }

        It 'Leaves the Web Server source security descriptor unchanged' {
            (Get-TemplateSddl -Name 'WebServer') | Should -Be $script:SourceSddlBefore
        }

        AfterAll {
            $script:SourceBefore.Dispose()
        }
    }

    Context 'Idempotent redeploy' {
        It 'Replaces the owned clone with -Force and mints a fresh OID' {
            $first = Deploy-AGEsc4 -StatePath $script:StatePath -Force
            $second = Deploy-AGEsc4 -StatePath $script:StatePath -Force
            $second.CloneCn | Should -Be 'Test SSL'
            $second.Oid | Should -Not -Be $first.Oid
        }
    }
}
