#Requires -Modules Pester

<#
    Integration tests for the ESC1 scenario deploy (ticket #27).

    These run against the live lab forest and perform real AD writes, all
    ADCSGoat-owned and self-cleaning (AfterEach removes the clone, its
    companion OID object, and its publication entry). The Web Server source
    must be byte-identical before and after; that is asserted, not assumed.

    Run only where a writable lab DC is available. Skipped otherwise.
#>

BeforeDiscovery {
    $script:LabAvailable = $false
    try {
        $rootDSE = New-Object System.DirectoryServices.DirectoryEntry('LDAP://RootDSE')
        $null = $rootDSE.configurationNamingContext
        $script:LabAvailable = $true
    } catch {
        $script:LabAvailable = $false
    }
}

BeforeAll {
    . $PSScriptRoot/../Public/Deploy-AGEsc1.ps1
    . $PSScriptRoot/../Public/Copy-AGTemplate.ps1
    . $PSScriptRoot/../Private/New-AGTemplateOid.ps1
    . $PSScriptRoot/../Private/Remove-AGTemplate.ps1
    . $PSScriptRoot/../Private/Get-AGEnrollmentService.ps1
    . $PSScriptRoot/../Private/New-AGDeployState.ps1
    . $PSScriptRoot/../Private/Save-AGDeployState.ps1
    . $PSScriptRoot/../Private/Read-AGDeployState.ps1
    . $PSScriptRoot/../Private/Test-AGDeployPreflight.ps1

    Add-Type -AssemblyName System.DirectoryServices

    $script:RootDSE = New-Object System.DirectoryServices.DirectoryEntry('LDAP://RootDSE')
    $script:ConfigNC = $script:RootDSE.configurationNamingContext
    $script:TemplatesDN = "CN=Certificate Templates,CN=Public Key Services,CN=Services,$($script:ConfigNC)"
    $script:OidDN = "CN=OID,CN=Public Key Services,CN=Services,$($script:ConfigNC)"
    $script:CaDn = "CN=LabRootCA1,CN=Enrollment Services,CN=Public Key Services,CN=Services,$($script:ConfigNC)"
    $script:Ca = [pscustomobject]@{ Name = 'LabRootCA1'; FullName = 'ADCSGoat-CA.adcs.goat\LabRootCA1'; DistinguishedName = $script:CaDn }
    $script:StatePath = Join-Path -Path $TestDrive -ChildPath 'ADCSGoat.State.xml'
    $script:ClientAuthOid = '1.3.6.1.5.5.7.3.2'
    $script:EnrollGuid = [guid]'0e10c968-78fb-11d2-90d4-00c04f79dc55'

    function script:Get-TemplateEntry {
        param([string]$Name)
        $path = "LDAP://CN=$Name,$($script:TemplatesDN)"
        if ([System.DirectoryServices.DirectoryEntry]::Exists($path)) {
            $entry = New-Object System.DirectoryServices.DirectoryEntry($path)
            $entry.RefreshCache()
            $entry
        } else { $null }
    }

    function script:Get-TemplateSddl {
        param([string]$Name)
        $e = Get-TemplateEntry -Name $Name
        $s = $e.ObjectSecurity.GetSecurityDescriptorSddlForm([System.Security.AccessControl.AccessControlSections]::All)
        $e.Dispose()
        $s
    }

    function script:Remove-ScenarioClone {
        param([string]$Name)
        $entry = Get-TemplateEntry -Name $Name
        if ($null -ne $entry) {
            $oidValue = "$($entry.Properties['msPKI-Cert-Template-OID'].Value)"
            $entry.DeleteTree()
            $entry.Dispose()
            if ($oidValue) {
                $oidContainer = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:OidDN)")
                foreach ($child in @($oidContainer.Children)) {
                    if ("$($child.Properties['msPKI-Cert-Template-OID'].Value)" -eq $oidValue) { $child.DeleteTree() }
                    $child.Dispose()
                }
                $oidContainer.Dispose()
            }
        }
        # Unpublish from the CA: remove the single value from the multi-valued
        # certificateTemplates attribute and commit.
        $ca = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:CaDn)")
        $ca.RefreshCache()
        $current = @($ca.Properties['certificateTemplates'] | ForEach-Object { "$_" })
        if ($current -contains $Name) {
            $ca.Properties['certificateTemplates'].Remove($Name)
            $ca.CommitChanges()
        }
        $ca.Dispose()
    }
}

Describe 'Deploy-AGEsc1 (live forest)' -Skip:(-not $script:LabAvailable) {

    AfterAll {
        Remove-ScenarioClone -Name 'Copy of Web Server'
        Remove-ScenarioClone -Name 'Copy of Web Server Generated by ADCSGoat'
        Remove-Item -Path $script:StatePath -ErrorAction Ignore
    }

    Context 'When deployed against the single-CA lab' {
        BeforeAll {
            # Source capture BEFORE deploy, for the no-writes-landed proof.
            $script:SourceBefore = Get-TemplateEntry -Name 'WebServer'
            $script:SourcePropsBefore = @{}
            foreach ($p in $script:SourceBefore.Properties.PropertyNames) {
                $script:SourcePropsBefore[$p] = @($script:SourceBefore.Properties[$p] | ForEach-Object { "$_" }) | Sort-Object
            }
            $script:SourceSddlBefore = $script:SourceBefore.ObjectSecurity.GetSecurityDescriptorSddlForm([System.Security.AccessControl.AccessControlSections]::All)

            $script:Result = Deploy-AGEsc1 -StatePath $script:StatePath -Force
            $script:Clone = Get-TemplateEntry -Name $script:Result.CloneCn
        }

        It 'Creates the clone at the expected name' {
            $script:Result.CloneCn | Should -Be 'Copy of Web Server'
            $script:Clone | Should -Not -BeNullOrEmpty
        }

        It 'Appends Client Auth to pKIExtendedKeyUsage, preserving Server Auth' {
            $eku = @($script:Clone.Properties['pKIExtendedKeyUsage'] | ForEach-Object { "$_" })
            $eku | Should -Contain $script:ClientAuthOid
            $eku | Should -Contain '1.3.6.1.5.5.7.3.1'   # Server Auth preserved
        }

        It 'Appends Client Auth to msPKI-Certificate-Application-Policy, preserving Server Auth' {
            $ap = @($script:Clone.Properties['msPKI-Certificate-Application-Policy'] | ForEach-Object { "$_" })
            $ap | Should -Contain $script:ClientAuthOid
            $ap | Should -Contain '1.3.6.1.5.5.7.3.1'
        }

        It 'Keeps the name-flag ENROLLEE_SUPPLIES_SUBJECT bit (0x1) intact' {
            $flag = [int]$script:Clone.Properties['msPKI-Certificate-Name-Flag'].Value
            ($flag -band 0x1) | Should -Be 0x1
        }

        It 'Grants Domain Users the Enroll extended right' {
            $sddl = Get-TemplateSddl -Name $script:Result.CloneCn
            # Object ACE carrying the Enroll GUID (CR = control access /
            # extended right), granted to Domain Users. The trustee renders as
            # the well-known 'DU' alias or the full domain SID depending on the
            # source DACL the kernel copied.
            $enrollOid = $script:EnrollGuid.ToString()
            $sddl | Should -Match "\(OA;;CR;$enrollOid;;(DU|S-1-5-21-\d+-\d+-\d+-513)\)"
        }

        It 'Grants Domain Users Read' {
            $sddl = Get-TemplateSddl -Name $script:Result.CloneCn
            # Read rights (any combination of LC/RP/LO/RC/GR) for Domain Users.
            $sddl | Should -Match "\(A;;(GR|LCRPLORC);;;(DU|S-1-5-21-\d+-\d+-\d+-513)\)"
        }

        It 'Publishes the clone cn in the selected CA certificateTemplates' {
            $ca = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:CaDn)")
            $published = @($ca.Properties['certificateTemplates'] | ForEach-Object { "$_" })
            $ca.Dispose()
            $published | Should -Contain $script:Result.CloneCn
        }

        It 'Records the clone in the state file (cn, OID, companion DN)' {
            $state = Read-AGDeployState -Path $script:StatePath
            $records = @($state.Clones | Where-Object { $_.Scenario -eq 'ESC1' })
            $records | Should -HaveCount 1
            $records[0].Cn | Should -Be $script:Result.CloneCn
            $records[0].Oid | Should -Be $script:Result.Oid
            $records[0].CompanionOidObjectDN | Should -Match 'CN=OID'
        }

        It 'Leaves the Web Server source attributes unchanged' {
            $sourceAfter = Get-TemplateEntry -Name 'WebServer'
            foreach ($p in $sourceAfter.Properties.PropertyNames) {
                $after = @($sourceAfter.Properties[$p] | ForEach-Object { "$_" }) | Sort-Object
                ($after -join '|') | Should -Be (($script:SourcePropsBefore[$p]) -join '|') -Because "source attribute '$p' must not change"
            }
            $sourceAfter.Dispose()
        }

        It 'Leaves the Web Server source security descriptor unchanged' {
            (Get-TemplateSddl -Name 'WebServer') | Should -Be $script:SourceSddlBefore
        }

        AfterAll {
            $script:SourceBefore.Dispose()
        }
    }

    Context 'When Domain Users already holds the rights (idempotent redeploy)' {
        It 'Replaces the owned clone without error and re-enforces state' {
            $first = Deploy-AGEsc1 -StatePath $script:StatePath -Force
            $second = Deploy-AGEsc1 -StatePath $script:StatePath -Force
            $second.CloneCn | Should -Be 'Copy of Web Server'
            # Fresh OID proves delete+recreate, not in-place edit.
            $second.Oid | Should -Not -Be $first.Oid
        }
    }
}
