#Requires -Modules Pester

<#
    Integration tests for the ESC4-on-unpublished-template + ESC5-on-CA-object
    chain (ticket #30).

    "Copy of Workstation" is a verbatim Workstation Authentication clone with
    Domain Users Full Control, deliberately NOT published on the CA. The ESC5
    half grants Authenticated Users Full Control on the CA's
    pKIEnrollmentService directory object. These tests run against the live lab
    forest and are self-cleaning.
#>

BeforeDiscovery {
    $script:LabAvailable = $false
    try {
        $rootDSE = New-Object System.DirectoryServices.DirectoryEntry('LDAP://RootDSE')
        $null = $rootDSE.configurationNamingContext
        $script:LabAvailable = $true
    } catch {
        $script:LabAvailable = $false
    }
}

BeforeAll {
    . $PSScriptRoot/../Public/Deploy-AGEsc5Chain.ps1
    . $PSScriptRoot/../Private/Copy-AGTemplate.ps1
    . $PSScriptRoot/../Private/New-AGTemplateOid.ps1
    . $PSScriptRoot/../Private/Remove-AGTemplate.ps1
    . $PSScriptRoot/../Private/Get-AGEnrollmentService.ps1
    . $PSScriptRoot/../Private/Get-ADDomainNameFromNc.ps1
    . $PSScriptRoot/../Private/New-AGDeployState.ps1
    . $PSScriptRoot/../Private/Save-AGDeployState.ps1
    . $PSScriptRoot/../Private/Read-AGDeployState.ps1
    . $PSScriptRoot/../Private/Invoke-AGTemplateScenario.ps1
    . $PSScriptRoot/../Private/Invoke-AGDeployTeardown.ps1
    . $PSScriptRoot/../Private/Set-AGEnrollmentServiceAce.ps1

    Add-Type -AssemblyName System.DirectoryServices

    $script:RootDSE = New-Object System.DirectoryServices.DirectoryEntry('LDAP://RootDSE')
    $script:ConfigNC = $script:RootDSE.configurationNamingContext
    $script:TemplatesDN = "CN=Certificate Templates,CN=Public Key Services,CN=Services,$($script:ConfigNC)"
    $script:OidDN = "CN=OID,CN=Public Key Services,CN=Services,$($script:ConfigNC)"
    $script:CaDn = "CN=LabRootCA1,CN=Enrollment Services,CN=Public Key Services,CN=Services,$($script:ConfigNC)"
    $script:StatePath = Join-Path -Path $TestDrive -ChildPath 'ADCSGoat.State.xml'

    # Attributes the kernel legitimately governs on the clone (identity, fresh
    # OID, schema upgrade, revision counters, ownership marker).
    $script:KernelGoverned = @(
        'cn','name','displayName','distinguishedName','objectGUID',
        'msPKI-Cert-Template-OID','msPKI-Template-Schema-Version','revision',
        'msPKI-Template-Minor-Revision','description','whenCreated','whenChanged',
        'uSNCreated','uSNChanged','instanceType','dSCorePropagationData',
        'nTSecurityDescriptor','objectClass','objectCategory'
    )

    function script:Get-TemplateEntry {
        param([string]$Name)
        $path = "LDAP://CN=$Name,$($script:TemplatesDN)"
        if ([System.DirectoryServices.DirectoryEntry]::Exists($path)) {
            $entry = New-Object System.DirectoryServices.DirectoryEntry($path)
            $entry.RefreshCache()
            $entry
        } else { $null }
    }

    function script:Get-CaPublished {
        $ca = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:CaDn)")
        $ca.RefreshCache()
        $published = @($ca.Properties['certificateTemplates'] | ForEach-Object { "$_" })
        $ca.Dispose()
        $published
    }

    function script:Get-CaSddl {
        $ca = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:CaDn)")
        $ca.RefreshCache()
        $sddl = $ca.ObjectSecurity.GetSecurityDescriptorSddlForm([System.Security.AccessControl.AccessControlSections]::All)
        $ca.Dispose()
        $sddl
    }

    function script:Remove-ScenarioClone {
        param([string]$Name)
        $entry = Get-TemplateEntry -Name $Name
        if ($null -ne $entry) {
            $oidValue = "$($entry.Properties['msPKI-Cert-Template-OID'].Value)"
            $entry.DeleteTree()
            $entry.Dispose()
            if ($oidValue) {
                $oidContainer = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:OidDN)")
                foreach ($child in @($oidContainer.Children)) {
                    if ("$($child.Properties['msPKI-Cert-Template-OID'].Value)" -eq $oidValue) { $child.DeleteTree() }
                    $child.Dispose()
                }
                $oidContainer.Dispose()
            }
        }
    }
}

Describe 'Deploy-AGEsc5Chain (live forest)' -Skip:(-not $script:LabAvailable) {

    BeforeAll {
        # True clean baseline, captured before ANY context mutates the CA object.
        $script:PreRunCaSddl = Get-CaSddl
    }
    AfterAll {
        # Self-clean: restore the CA descriptor captured before the run, strip
        # the clone cn, delete the clone + companion OID.
        Remove-ScenarioClone -Name 'Copy of Workstation'
        Remove-ScenarioClone -Name 'Copy of Workstation Generated by ADCSGoat'
        if ($script:PreRunCaSddl) {
            $ca = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:CaDn)")
            # Remove any AU GenericAll ACE the deploy left, then write the SD
            # back raw so inheritance/control flags survive (ObjectSecurity
            # round-trip can drop them).
            $sd = $ca.ObjectSecurity
            $au = New-Object System.Security.Principal.SecurityIdentifier('S-1-5-11')
            foreach ($ace in @($sd.Access)) {
                if ($ace.IdentityReference.Value -eq $au.Value -and $ace.ActiveDirectoryRights -eq [System.DirectoryServices.ActiveDirectoryRights]::GenericAll) {
                    $sd.RemoveAccessRule($ace) | Out-Null
                }
            }
            $ca.ObjectSecurity = $sd
            $ca.CommitChanges()
            $current = @($ca.Properties['certificateTemplates'] | ForEach-Object { "$_" })
            foreach ($cn in @('Copy of Workstation','Copy of Workstation Generated by ADCSGoat')) {
                if ($current -contains $cn) { $ca.Properties['certificateTemplates'].Remove($cn) }
            }
            $ca.CommitChanges()
            $ca.Dispose()
        }
        Remove-Item -Path $script:StatePath -ErrorAction Ignore
    }

    Context 'When deployed against the single-CA lab' {
        BeforeAll {
            $script:SourceBefore = Get-TemplateEntry -Name 'Workstation'
            $script:SourcePropsBefore = @{}
            foreach ($p in $script:SourceBefore.Properties.PropertyNames) {
                $script:SourcePropsBefore[$p] = @($script:SourceBefore.Properties[$p] | ForEach-Object { "$_" }) | Sort-Object
            }

            $script:Result = Deploy-AGEsc5Chain -StatePath $script:StatePath -Force
            $script:Clone = Get-TemplateEntry -Name $script:Result.CloneCn
        }

        It 'Creates the clone at the expected name' {
            $script:Result.CloneCn | Should -Be 'Copy of Workstation'
            $script:Clone | Should -Not -BeNullOrEmpty
        }

        It 'Applies zero attribute overrides beyond the kernel-governed set' {
            foreach ($p in $script:Clone.Properties.PropertyNames) {
                if ($script:KernelGoverned -contains $p) { continue }
                $cloneVals = @($script:Clone.Properties[$p] | ForEach-Object { "$_" }) | Sort-Object
                $srcVals = $script:SourcePropsBefore[$p]
                ($cloneVals -join '|') | Should -Be ($srcVals -join '|') -Because "the chain makes no attribute override on '$p'"
            }
        }

        It 'Grants Domain Users Full Control (GenericAll) on the clone' {
            $sddl = $script:Clone.ObjectSecurity.GetSecurityDescriptorSddlForm([System.Security.AccessControl.AccessControlSections]::All)
            $sddl | Should -Match "\(A;;(GA|CCDCLCSWRPWPDTLO[A-Z]*CRSDRCWDWO);;;(DU|S-1-5-21-\d+-\d+-\d+-513)\)"
        }

        It 'Does NOT publish the clone cn in the selected CA certificateTemplates' {
            (Get-CaPublished) | Should -Not -Contain $script:Result.CloneCn
        }

        It 'Results in Authenticated Users Full Control on the CA pKIEnrollmentService object' {
            # The end-state required by ESC5. This lab's CA already carries an
            # inherited AU Full Control ACE from the Enrollment Services
            # container, so this asserts the resulting state, not that the
            # deploy added it; the deploy's own add/dedupe logic is covered by
            # the offline Test-AGAccessRulePresent tests.
            (Get-CaSddl) | Should -Match "\(A;;(GA|CCDCLCSWRPWPDTLO[A-Z]*CRSDRCWDWO);;;(AU|S-1-5-11)\)"
        }

        It 'Records the clone in the state file' {
            $state = Read-AGDeployState -Path $script:StatePath
            $records = @($state.Clones | Where-Object { $_.Scenario -eq 'ESC5Chain' })
            $records | Should -HaveCount 1
            $records[0].Cn | Should -Be $script:Result.CloneCn
        }

        It 'Leaves the Workstation source attributes unchanged' {
            $sourceAfter = Get-TemplateEntry -Name 'Workstation'
            foreach ($p in $sourceAfter.Properties.PropertyNames) {
                if ($p -eq 'nTSecurityDescriptor') { continue }
                $after = @($sourceAfter.Properties[$p] | ForEach-Object { "$_" }) | Sort-Object
                ($after -join '|') | Should -Be (($script:SourcePropsBefore[$p]) -join '|') -Because "source attribute '$p' must not change"
            }
            $sourceAfter.Dispose()
        }

        AfterAll {
            $script:SourceBefore.Dispose()
            if ($script:Clone) { $script:Clone.Dispose() }
        }
    }

    Context 'Pristine-state redeploy after an exercise published the clone' {
        It 'Strips the published cn from certificateTemplates on redeploy' {
            # Simulate the exercise: publish the clone via the CA object.
            $ca = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:CaDn)")
            $ca.RefreshCache()
            $published = @($ca.Properties['certificateTemplates'] | ForEach-Object { "$_" })
            if ($published -notcontains 'Copy of Workstation') {
                $ca.PutEx(3, 'certificateTemplates', @('Copy of Workstation'))
                $ca.SetInfo()
            }
            $ca.Dispose()
            (Get-CaPublished) | Should -Contain 'Copy of Workstation'

            # Redeploy enforces the unpublished pristine state.
            Deploy-AGEsc5Chain -StatePath $script:StatePath -Force
            (Get-CaPublished) | Should -Not -Contain 'Copy of Workstation'
        }
    }

    Context 'Teardown (ACL-last)' {
        It 'Restores the CA security descriptor byte-for-byte and removes the clone' {
            # NOTE: this lab's CA carries an inherited Authenticated Users Full
            # Control ACE from the Enrollment Services container, so the ESC5
            # grant is a no-op here and its presence/absence is not a usable
            # signal. The verifiable contract is byte-exact restoration of the
            # pre-deploy descriptor plus removal of the clone.
            if (Test-Path -Path $script:StatePath) { Remove-Item -Path $script:StatePath -Force }
            $preDeploy = Get-CaSddl
            Deploy-AGEsc5Chain -StatePath $script:StatePath -Force | Out-Null
            (Get-TemplateEntry -Name 'Copy of Workstation') | Should -Not -BeNullOrEmpty -Because 'deploy must create the clone before teardown'

            Invoke-AGDeployTeardown -StatePath $script:StatePath

            (Get-CaSddl) | Should -Be $preDeploy -Because 'teardown byte-restores the pre-change descriptor captured in the state file'
            (Get-TemplateEntry -Name 'Copy of Workstation') | Should -BeNullOrEmpty
            (Get-CaPublished) | Should -Not -Contain 'Copy of Workstation'
        }
    }
}
