#Requires -Modules Pester

<#
    Integration tests for the ESC3 chain scenario deploy (ticket #29).

    "VMware 6.x" is a SubCA clone with NO EKU override (the no-EKU profile
    satisfies the Certificate-Request-Agent check). Authenticated Users get
    Read + Enroll. The built-in User template is published if absent, ACL
    unchanged. These tests run against the live lab forest and are
    self-cleaning; User is already published on this lab, so the deploy must
    leave it published and byte-identical.
#>

BeforeDiscovery {
    $script:LabAvailable = $false
    try {
        $rootDSE = New-Object System.DirectoryServices.DirectoryEntry('LDAP://RootDSE')
        $null = $rootDSE.configurationNamingContext
        $script:LabAvailable = $true
    } catch {
        $script:LabAvailable = $false
    }
}

BeforeAll {
    . $PSScriptRoot/../Public/Deploy-AGEsc3Chain.ps1
    . $PSScriptRoot/../Private/Copy-AGTemplate.ps1
    . $PSScriptRoot/../Private/New-AGTemplateOid.ps1
    . $PSScriptRoot/../Private/Remove-AGTemplate.ps1
    . $PSScriptRoot/../Private/Get-AGEnrollmentService.ps1
    . $PSScriptRoot/../Private/New-AGDeployState.ps1
    . $PSScriptRoot/../Private/Save-AGDeployState.ps1
    . $PSScriptRoot/../Private/Read-AGDeployState.ps1
    . $PSScriptRoot/../Private/Get-ADDomainNameFromNc.ps1
    . $PSScriptRoot/../Private/Invoke-AGTemplateScenario.ps1

    Add-Type -AssemblyName System.DirectoryServices

    $script:RootDSE = New-Object System.DirectoryServices.DirectoryEntry('LDAP://RootDSE')
    $script:ConfigNC = $script:RootDSE.configurationNamingContext
    $script:TemplatesDN = "CN=Certificate Templates,CN=Public Key Services,CN=Services,$($script:ConfigNC)"
    $script:OidDN = "CN=OID,CN=Public Key Services,CN=Services,$($script:ConfigNC)"
    $script:CaDn = "CN=LabRootCA1,CN=Enrollment Services,CN=Public Key Services,CN=Services,$($script:ConfigNC)"
    $script:StatePath = Join-Path -Path $TestDrive -ChildPath 'ADCSGoat.State.xml'
    $script:EnrollGuid = '0e10c968-78fb-11d2-90d4-00c04f79dc55'
    $script:AuthenticatedUsersSid = 'S-1-5-11'
    # NTAuthCertificates object DN — VMware 6.x must never appear here.
    $script:NtAuthDn = "CN=NTAuthCertificates,CN=Public Key Services,CN=Services,$($script:ConfigNC)"

    function script:Get-TemplateEntry {
        param([string]$Name)
        $path = "LDAP://CN=$Name,$($script:TemplatesDN)"
        if ([System.DirectoryServices.DirectoryEntry]::Exists($path)) {
            $entry = New-Object System.DirectoryServices.DirectoryEntry($path)
            $entry.RefreshCache()
            $entry
        } else { $null }
    }

    function script:Get-TemplateSddl {
        param([string]$Name)
        $e = Get-TemplateEntry -Name $Name
        $s = $e.ObjectSecurity.GetSecurityDescriptorSddlForm([System.Security.AccessControl.AccessControlSections]::All)
        $e.Dispose()
        $s
    }

    function script:Remove-ScenarioClone {
        param([string]$Name)
        $entry = Get-TemplateEntry -Name $Name
        if ($null -ne $entry) {
            $oidValue = "$($entry.Properties['msPKI-Cert-Template-OID'].Value)"
            $entry.DeleteTree()
            $entry.Dispose()
            if ($oidValue) {
                $oidContainer = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:OidDN)")
                foreach ($child in @($oidContainer.Children)) {
                    if ("$($child.Properties['msPKI-Cert-Template-OID'].Value)" -eq $oidValue) { $child.DeleteTree() }
                    $child.Dispose()
                }
                $oidContainer.Dispose()
            }
        }
        $ca = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:CaDn)")
        $ca.RefreshCache()
        $current = @($ca.Properties['certificateTemplates'] | ForEach-Object { "$_" })
        if ($current -contains $Name) {
            $ca.Properties['certificateTemplates'].Remove($Name)
            $ca.CommitChanges()
        }
        $ca.Dispose()
    }
}

Describe 'Deploy-AGEsc3Chain (live forest)' -Skip:(-not $script:LabAvailable) {

    AfterAll {
        Remove-ScenarioClone -Name 'VMware 6.x'
        Remove-ScenarioClone -Name 'VMware 6.x Generated by ADCSGoat'
        Remove-Item -Path $script:StatePath -ErrorAction Ignore
    }

    Context 'When deployed against the single-CA lab' {
        BeforeAll {
            # Capture sources BEFORE deploy for the no-writes-landed proof.
            $script:SubcaBefore = Get-TemplateEntry -Name 'SubCA'
            $script:SubcaPropsBefore = @{}
            foreach ($p in $script:SubcaBefore.Properties.PropertyNames) {
                $script:SubcaPropsBefore[$p] = @($script:SubcaBefore.Properties[$p] | ForEach-Object { "$_" }) | Sort-Object
            }
            $script:SubcaSddlBefore = $script:SubcaBefore.ObjectSecurity.GetSecurityDescriptorSddlForm([System.Security.AccessControl.AccessControlSections]::All)

            $script:UserSddlBefore = Get-TemplateSddl -Name 'User'

            $script:Result = Deploy-AGEsc3Chain -StatePath $script:StatePath -Force
            $script:Clone = Get-TemplateEntry -Name $script:Result.CloneCn
        }

        It 'Creates the clone at the expected name' {
            $script:Result.CloneCn | Should -Be 'VMware 6.x'
            $script:Clone | Should -Not -BeNullOrEmpty
        }

        It 'Is schema v2 (GUI-authentic upgrade of the v1 source)' {
            [int]$script:Clone.Properties['msPKI-Template-Schema-Version'].Value | Should -Be 2
        }

        It 'Adds no EKU to pKIExtendedKeyUsage (no-EKU profile preserved)' {
            $eku = @($script:Clone.Properties['pKIExtendedKeyUsage'] | ForEach-Object { "$_" })
            $eku | Should -BeNullOrEmpty
        }

        It 'Adds no EKU to msPKI-Certificate-Application-Policy (no Certificate-Request-Agent OID)' {
            $ap = @($script:Clone.Properties['msPKI-Certificate-Application-Policy'] | ForEach-Object { "$_" })
            $ap | Should -BeNullOrEmpty
        }

        It 'Grants Authenticated Users the Enroll extended right' {
            $sddl = Get-TemplateSddl -Name $script:Result.CloneCn
            # Object ACE: (OA;;CR;<EnrollGUID>;;AU) - AU is the S-1-5-11 alias.
            $sddl | Should -Match "\(OA;;CR;$($script:EnrollGuid);;AU\)"
        }

        It 'Grants Authenticated Users Read' {
            $sddl = Get-TemplateSddl -Name $script:Result.CloneCn
            # Read may render as GR or the decomposed LCRPLORC mask.
            $sddl | Should -Match "\(A;;(GR|LCRPLORC);;;AU\)"
        }

        It 'Publishes VMware 6.x on the selected CA' {
            $ca = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:CaDn)")
            $ca.RefreshCache()
            $published = @($ca.Properties['certificateTemplates'] | ForEach-Object { "$_" })
            $ca.Dispose()
            $published | Should -Contain $script:Result.CloneCn
        }

        It 'Leaves the built-in User template published on the selected CA' {
            $ca = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:CaDn)")
            $ca.RefreshCache()
            $published = @($ca.Properties['certificateTemplates'] | ForEach-Object { "$_" })
            $ca.Dispose()
            $published | Should -Contain 'User'
        }

        It "Leaves the built-in User template's security descriptor byte-identical" {
            (Get-TemplateSddl -Name 'User') | Should -Be $script:UserSddlBefore
        }

        It 'Never touches NTAuthCertificates' {
            # VMware 6.x is a template, not a CA cert; the deploy performs no
            # write to NTAuthCertificates. Prove the object is unmodified by
            # comparing its cacertificate count and whenChanged across a fresh
            # deploy.
            $ntAuthBefore = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:NtAuthDn)")
            $ntAuthBefore.RefreshCache()
            $cacertsBefore = @($ntAuthBefore.Properties['cacertificate']).Count
            $whenChangedBefore = "$($ntAuthBefore.Properties['whenChanged'].Value)"
            $ntAuthBefore.Dispose()

            Deploy-AGEsc3Chain -StatePath $script:StatePath -Force | Out-Null

            $ntAuthAfter = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$($script:NtAuthDn)")
            $ntAuthAfter.RefreshCache()
            $cacertsAfter = @($ntAuthAfter.Properties['cacertificate']).Count
            $whenChangedAfter = "$($ntAuthAfter.Properties['whenChanged'].Value)"
            $ntAuthAfter.Dispose()

            $cacertsAfter | Should -Be $cacertsBefore
            $whenChangedAfter | Should -Be $whenChangedBefore
        }

        It 'Records the clone in the state file (cn, OID, companion DN)' {
            $state = Read-AGDeployState -Path $script:StatePath
            # The state file accumulates one record per deploy; the NTAuth test
            # above redeploys, so match on this run's OID, not a bare count.
            $records = @($state.Clones | Where-Object { $_.Scenario -eq 'ESC3Chain' -and $_.Oid -eq $script:Result.Oid })
            $records | Should -HaveCount 1
            $records[0].Cn | Should -Be $script:Result.CloneCn
            $records[0].CompanionOidObjectDN | Should -Match 'CN=OID'
        }

        It 'Leaves the SubCA source attributes unchanged' {
            $sourceAfter = Get-TemplateEntry -Name 'SubCA'
            foreach ($p in $sourceAfter.Properties.PropertyNames) {
                $after = @($sourceAfter.Properties[$p] | ForEach-Object { "$_" }) | Sort-Object
                ($after -join '|') | Should -Be (($script:SubcaPropsBefore[$p]) -join '|') -Because "source attribute '$p' must not change"
            }
            $sourceAfter.Dispose()
        }

        It 'Leaves the SubCA source security descriptor unchanged' {
            (Get-TemplateSddl -Name 'SubCA') | Should -Be $script:SubcaSddlBefore
        }

        AfterAll {
            $script:SubcaBefore.Dispose()
        }
    }

    Context 'Idempotent redeploy' {
        It 'Replaces the owned clone with -Force and mints a fresh OID' {
            $first = Deploy-AGEsc3Chain -StatePath $script:StatePath -Force
            $second = Deploy-AGEsc3Chain -StatePath $script:StatePath -Force
            $second.CloneCn | Should -Be 'VMware 6.x'
            $second.Oid | Should -Not -Be $first.Oid
        }
    }
}
