function Copy-AGTemplate {
    <#
    .SYNOPSIS
        Clones a built-in certificate template to a new ADCSGoat-owned template.

    .DESCRIPTION
        Implements the universal clone rules settled in ADCSGoat issue #22 and
        the collision contract from issue #23.

        Clone rules:
        - Identity/system attributes are never copied (cn, name, objectClass,
          objectGUID, distinguishedName, instanceType, whenCreated/whenChanged,
          uSNCreated/uSNChanged, dSCorePropagationData, nTSecurityDescriptor,
          objectCategory, showInAdvancedViewOnly, displayName,
          msPKI-Cert-Template-OID). cn/name/displayName are set to the
          destination identity; every other attribute is copied verbatim from
          the live source (read-and-preserve).
        - A fresh OID is minted under the forest base arc with a companion
          ms-PKI-Enterprise-Oid object (see New-AGTemplateOid).
        - GUI-authentic schema upgrade: a schema-v1 source produces a schema-v2
          clone; v2+ sources copy verbatim. revision and
          msPKI-Template-Minor-Revision are set to fresh initial values.
        - The source's whole security descriptor (owner, group, DACL, SACL,
          protected bit) is applied atomically via ObjectSecurity.
        - The clone's description carries the 'Generated by ADCSGoat'
          ownership marker.

        Collision contract:
        - Owned collision (existing object with the ownership marker):
          interactive runs prompt Replace/Cancel with Cancel as default;
          non-interactive runs abort unless -Force is passed.
        - Unowned collision (existing object without the marker): the object
          is never touched; the clone lands at the deterministic fallback name
          '<DestinationName> Generated by ADCSGoat'.
        - Replace is delete + recreate. A failure after the delete aborts
          loudly, naming the deleted object and the failed step; no rollback
          machinery (rerun to recreate).

    .PARAMETER SourceName
        The cn of the built-in source template (e.g. 'WebServer', 'SubCA').

    .PARAMETER DestinationName
        The desired cn/displayName of the clone.

    .PARAMETER Server
        The domain controller to write to. Defaults to the logon server.

    .PARAMETER Force
        Replaces an owned collision without prompting. Required for
        non-interactive replacement.

    .OUTPUTS
        System.Management.Automation.PSCustomObject. The resolved clone
        identity: DestinationName (actual, post-fallback), Oid, and
        CompanionOidObjectDN.

    .EXAMPLE
        Copy-AGTemplate -SourceName 'WebServer' -DestinationName 'Copy of Web Server'

    .EXAMPLE
        Copy-AGTemplate -SourceName 'SubCA' -DestinationName 'VMware 6.x' -Force
    #>
    [CmdletBinding()]
    param (
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [string]$SourceName,

        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [string]$DestinationName,

        [Parameter()]
        [ValidateNotNullOrEmpty()]
        [string]$Server,

        [Parameter()]
        [switch]$Force
    )

    begin {
        Add-Type -AssemblyName System.DirectoryServices

        if ([string]::IsNullOrEmpty($Server)) {
            $Server = [System.Net.Dns]::GetHostEntry($env:LOGONSERVER.TrimStart('\')).HostName
        }

        $rootDSE = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$Server/RootDSE")
        $configurationPartition = $rootDSE.configurationNamingContext
        $templatesContainerDN = "CN=Certificate Templates,CN=Public Key Services,CN=Services,$configurationPartition"

        $skipList = @(
            'cn', 'name', 'objectClass', 'objectGUID', 'distinguishedName',
            'instanceType', 'whenCreated', 'whenChanged', 'uSNCreated',
            'uSNChanged', 'dSCorePropagationData', 'nTSecurityDescriptor',
            'objectCategory', 'showInAdvancedViewOnly', 'displayName',
            'msPKI-Cert-Template-OID'
        )

        function Test-IsOwned {
            param([System.DirectoryServices.DirectoryEntry]$Entry)
            "$($Entry.Properties['description'].Value)" -match 'Generated by ADCSGoat'
        }

    }

    process {
        $templatesContainer = New-Object System.DirectoryServices.DirectoryEntry("LDAP://$Server/$templatesContainerDN")

        # Resolve the source template.
        $sourcePath = "LDAP://$Server/CN=$SourceName,$templatesContainerDN"
        if (-not [System.DirectoryServices.DirectoryEntry]::Exists($sourcePath)) {
            $templatesContainer.Dispose()
            throw "Source template '$SourceName' not found at 'CN=$SourceName,$templatesContainerDN'."
        }
        $source = New-Object System.DirectoryServices.DirectoryEntry($sourcePath)
        $source.RefreshCache()

        # Collision resolution: decide the actual destination name up front.
        $resolvedName = $DestinationName
        $destinationPath = "LDAP://$Server/CN=$resolvedName,$templatesContainerDN"

        if ([System.DirectoryServices.DirectoryEntry]::Exists($destinationPath)) {
            $existing = New-Object System.DirectoryServices.DirectoryEntry($destinationPath)
            $owned = Test-IsOwned -Entry $existing
            $existing.Dispose()

            if ($owned) {
                $replace = $Force.IsPresent
                if (-not $replace) {
                    $interactive = [System.Environment]::UserInteractive -and -not [System.Console]::IsInputRedirected
                    if ($interactive) {
                        $title = "Template '$resolvedName' already exists and is ADCSGoat-owned."
                        $message = 'Replace it (delete + recreate)?'
                        $choiceReplace = New-Object System.Management.Automation.Host.ChoiceDescription '&Replace', 'Delete the owned object and recreate it from the source.'
                        $choiceCancel = New-Object System.Management.Automation.Host.ChoiceDescription '&Cancel', 'Abort without changes.'
                        $decision = $Host.UI.PromptForChoice($title, $message, @($choiceReplace, $choiceCancel), 1)
                        $replace = ($decision -eq 0)
                    }
                }
                if (-not $replace) {
                    $templatesContainer.Dispose()
                    $source.Dispose()
                    throw "Collision: '$resolvedName' exists and is ADCSGoat-owned; replacement was not confirmed. Rerun interactively or pass -Force."
                }
                # Owned replace: delete the existing object now; recreate below.
                try {
                    Remove-AGTemplate -Name $resolvedName
                } catch {
                    $templatesContainer.Dispose()
                    $source.Dispose()
                    throw "Replace of owned template '$resolvedName' failed during delete: $($_.Exception.Message)"
                }
            } else {
                # Unowned collision: never touch; fall back to the marked name.
                $resolvedName = "$DestinationName Generated by ADCSGoat"
                Write-Warning "'$DestinationName' exists and is not ADCSGoat-owned; it will not be modified. Using fallback name '$resolvedName'."
                $destinationPath = "LDAP://$Server/CN=$resolvedName,$templatesContainerDN"
                if ([System.DirectoryServices.DirectoryEntry]::Exists($destinationPath)) {
                    $fallbackEntry = New-Object System.DirectoryServices.DirectoryEntry($destinationPath)
                    $fallbackOwned = Test-IsOwned -Entry $fallbackEntry
                    $fallbackEntry.Dispose()
                    if ($fallbackOwned) {
                        $replace = $Force.IsPresent
                        if (-not $replace) {
                            $interactive = [System.Environment]::UserInteractive -and -not [System.Console]::IsInputRedirected
                            if ($interactive) {
                                $title = "Fallback template '$resolvedName' already exists and is ADCSGoat-owned."
                                $message = 'Replace it (delete + recreate)?'
                                $choiceReplace = New-Object System.Management.Automation.Host.ChoiceDescription '&Replace', 'Delete the owned object and recreate it from the source.'
                                $choiceCancel = New-Object System.Management.Automation.Host.ChoiceDescription '&Cancel', 'Abort without changes.'
                                $decision = $Host.UI.PromptForChoice($title, $message, @($choiceReplace, $choiceCancel), 1)
                                $replace = ($decision -eq 0)
                            }
                        }
                        if (-not $replace) {
                            $templatesContainer.Dispose()
                            $source.Dispose()
                            throw "Collision: '$resolvedName' exists and is ADCSGoat-owned; replacement was not confirmed. Rerun interactively or pass -Force."
                        }
                        try {
                            Remove-AGTemplate -Name $resolvedName
                        } catch {
                            $templatesContainer.Dispose()
                            $source.Dispose()
                            throw "Replace of owned template '$resolvedName' failed during delete: $($_.Exception.Message)"
                        }
                    } else {
                        $templatesContainer.Dispose()
                        $source.Dispose()
                        throw "Collision: both '$DestinationName' and fallback '$resolvedName' exist and are not ADCSGoat-owned. Resolve the foreign objects manually."
                    }
                }
            }
        }

            # Mint the OID + companion object first (fail fast before any template write).
            $templateOid = New-AGTemplateOid -TemplateName $resolvedName -Server $Server

            $clone = $null
            try {
                $clone = $templatesContainer.Children.Add("CN=$resolvedName", 'pKICertificateTemplate')

                # Verbatim copy of every non-excluded attribute.
                foreach ($propertyName in $source.Properties.PropertyNames) {
                    if ($skipList -contains $propertyName) { continue }
                    $sourceValues = $source.Properties[$propertyName]
                    if ($null -eq $sourceValues -or $sourceValues.Count -eq 0) { continue }
                    foreach ($value in $sourceValues) {
                        $clone.Properties[$propertyName].Add($value) | Out-Null
                    }
                }

                # Destination identity + ownership marker.
                $clone.Properties['displayName'].Value = $resolvedName
                $clone.Properties['description'].Value = 'Generated by ADCSGoat'

                # GUI-authentic schema upgrade: v1 sources become v2 clones.
                $sourceSchema = 0
                if ($source.Properties['msPKI-Template-Schema-Version'].Count -gt 0) {
                    $sourceSchema = [int]$source.Properties['msPKI-Template-Schema-Version'].Value
                }
                if ($sourceSchema -lt 2) {
                    $clone.Properties['msPKI-Template-Schema-Version'].Value = 2
                }

                # Fresh revision counters.
                $clone.Properties['revision'].Value = 100
                $clone.Properties['msPKI-Template-Minor-Revision'].Value = 0

                # Fresh OID.
                $clone.Properties['msPKI-Cert-Template-OID'].Value = $templateOid

                $clone.CommitChanges()

                # Whole source security descriptor, one atomic write.
                $clone.ObjectSecurity = $source.ObjectSecurity
                $clone.CommitChanges()
            } catch {
                $failedName = $resolvedName
                if ($null -ne $clone) { $clone.Dispose() }
                $templatesContainer.Dispose()
                $source.Dispose()
                throw "Clone of '$SourceName' to '$failedName' failed during recreate after any owned delete: $($_.Exception.Message). Rerun the deploy to recreate."
            }

            $clone.Dispose()

        $templatesContainer.Dispose()
        $source.Dispose()

        $companionOidDN = $null
        if (-not [string]::IsNullOrEmpty($templateOid)) {
            $oidContainerDN = "CN=OID,CN=Public Key Services,CN=Services,$configurationPartition"
            $companionOidDN = "ms-PKI-Enterprise-Oid for $templateOid under $oidContainerDN"
        }

        Write-Output ([pscustomobject]@{
            SourceName          = $SourceName
            DestinationName     = $resolvedName
            RequestedName       = $DestinationName
            Oid                 = $templateOid
            CompanionOidObject  = $companionOidDN
        })
    }
}
